### ISSUE TITLE
Add-AADGroupLicenseAssignment not exported

### ISSUE THREAD

**Issue by TrixM** [nicolonsky/AzureADLicensing#1]
`Add-AADGroupLicenseAssignment` is not exported in AzureAdLicensing.psd1.

It's missing from both lines 72 and 75 in the `FunctionsToExport` and `CmdletsToExport` arrays

**Comment by nicolonsky** [comment]
Fixed this in https://github.com/nicolonsky/AzureADLicensing/commit/1c0fb76a857790fe76eb53ac152be917af05e46c

**Comment by TrixM** [comment]
Works fine on testing
