### ISSUE TITLE
Error not correctly returned on http error

### ISSUE THREAD

**Issue by TrixM** [nicolonsky/AzureADLicensing#2]
(Edited: got instance of JSON-containing error as well, so updated workaround)
In AzureAdLicensing.psm1, the correct http error is not returned if you get something like a 401 error when your token has expired. An error is returned instead about incorrectly-formatted JSON.

The current `catch` statement seems to be anticipating JSON data which is not always produced with that kind of exception. My workaround was to add another `if` statement to check whether `$_.ErrorDetails.Message` appears to have JSON in it.

```
try {
    $request = Invoke-WebRequest -Method Get -Uri $($baseUrl + "AccountSkus/Group/$groupId") -Headers $global:header
    $requestContent = $request | ConvertFrom-Json
    return $requestContent
}
catch {
    # convert the error message if it appears to be JSON
    if ($_.ErrorDetails.Message -like "{`"Classname*") {
        $local:errmsg = $_.ErrorDetails.Message | ConvertFrom-Json
        if ($local:errmsg.Clientdata.operationresults.details) {
            Write-Error $local:errmsg.Clientdata.operationresults.details
        }
        else {
            Write-Error $local:errmsg
        }
    }
    else {
        Write-Error $_.ErrorDetails.Message
    }
}
```

**Comment by nicolonsky** [comment]
Thanks for your enhancements. Added them in https://github.com/nicolonsky/AzureADLicensing/commit/1c0fb76a857790fe76eb53ac152be917af05e46c and also switched to the Az PowerShell Module because the AzureRM is deprecated.

**Comment by nicolonsky** [comment]
New module version is now available: https://www.powershellgallery.com/packages/AzureADLicensing

**Comment by TrixM** [comment]
Thanks for quick turnaround! Works fine on testing
