### ISSUE TITLE
feature request: Find-AADLicensedGroups

### ISSUE THREAD

**Issue by bartvermeersch** [nicolonsky/AzureADLicensing#3]
It would be very useful to have a command to retrieve all AADGroups with a license applied to it.

**Comment by nicolonsky** [comment]
Thanks for the feedback, will take this into consideration

**Comment by nicolonsky** [comment]
You can now use the `Get-AADGroupLicenseAssignment` cmdlet either with the `-All ` switch or `-groupId` parameter. 
The `-All ` option returns a list of all available licenses and the assignments:

![image](https://user-images.githubusercontent.com/32899754/88814678-bc360300-d1ba-11ea-9057-a84560b0ca5a.png)
