### ISSUE TITLE
Error not reporting correctly

### ISSUE THREAD

**Issue by Derek-Hartman** [nicolonsky/AzureADLicensing#7]
So, I ran Get-AADGroupLicenseAssignment on my specific group and it reported "hasErrors=; errorCount=0}}"

But if I look at the group in Azure it has 1 error currently
![image](https://user-images.githubusercontent.com/57258132/116585824-c5d5ce00-a8e6-11eb-9571-e63bee4dd4a0.png)

**Comment by nicolonsky** [comment]
The portal might use multiple APIs to display data and does not necessarily use the same request URL as the `Get-AADGroupLicenseAssignment`. Furthermore, the error count is displayed for each license assigned to a group, maybe you didn't look through all the output.
