### ISSUE TITLE
Add-AADGroupLicenseAssignment is not working

### ISSUE THREAD

**Issue by beatrizlourenco7** [nicolonsky/AzureADLicensing#8]
![image](https://user-images.githubusercontent.com/73603489/116921655-a3b3b700-ac2a-11eb-9d00-501a3bb76f96.png)
I already tried all the ways and the same error message appears

I also tried like the example 
Add-AADGroupLicenseAssignment -groupId "a5e95316-1c03-44d7-afac-efd0e788122c" -accountSkuId "nicolasuter:FLOW_FREE"
and the same massage appears

**Comment by nicolonsky** [comment]
Cannot really track issues like these without more details and repro steps, just tested it in a brand new tenant and had no issues. Maybe you don't have AAD Premium = no support for group-based licensing or you selected an invalid group / account SKU.
![image](https://user-images.githubusercontent.com/32899754/117362923-28693400-aebc-11eb-8e40-c106d28629db.png)

**Comment by beatrizlourenco7** [comment]
Hello Nicola, thanks for trying to help. 
I believe it has nothing to do with licensing and the group selected. 
I did it again and took another screenshot, let me know if you can see and understand better now:
![image](https://user-images.githubusercontent.com/73603489/117364677-94d03d00-ae94-11eb-9096-5ef42bb550a3.png)
